# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dlg_kunde.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QLabel, QLineEdit, QPlainTextEdit, QSizePolicy,
    QWidget)

class Ui_Dlg_Kunde(object):
    def setupUi(self, Dlg_Kunde):
        if not Dlg_Kunde.objectName():
            Dlg_Kunde.setObjectName(u"Dlg_Kunde")
        Dlg_Kunde.setWindowModality(Qt.WindowModality.WindowModal)
        Dlg_Kunde.resize(1222, 500)
        Dlg_Kunde.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.buttonBox = QDialogButtonBox(Dlg_Kunde)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(0, 430, 1211, 32))
        font = QFont()
        font.setPointSize(16)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.label = QLabel(Dlg_Kunde)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 110, 91, 21))
        self.label.setFont(font)
        self.Te_Anrede = QPlainTextEdit(Dlg_Kunde)
        self.Te_Anrede.setObjectName(u"Te_Anrede")
        self.Te_Anrede.setGeometry(QRect(130, 100, 41, 41))
        self.Te_Anrede.setFont(font)
        self.Te_Anrede.setTabChangesFocus(True)
        self.Te_Vorname = QPlainTextEdit(Dlg_Kunde)
        self.Te_Vorname.setObjectName(u"Te_Vorname")
        self.Te_Vorname.setGeometry(QRect(430, 100, 221, 41))
        self.Te_Vorname.setFont(font)
        self.Te_Vorname.setTabChangesFocus(True)
        self.label_3 = QLabel(Dlg_Kunde)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(700, 110, 111, 21))
        self.label_3.setFont(font)
        self.label_2 = QLabel(Dlg_Kunde)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(330, 110, 91, 21))
        self.label_2.setFont(font)
        self.Te_Nachname = QPlainTextEdit(Dlg_Kunde)
        self.Te_Nachname.setObjectName(u"Te_Nachname")
        self.Te_Nachname.setGeometry(QRect(810, 100, 381, 41))
        self.Te_Nachname.setFont(font)
        self.Te_Nachname.setTabChangesFocus(True)
        self.Te_Strasse = QPlainTextEdit(Dlg_Kunde)
        self.Te_Strasse.setObjectName(u"Te_Strasse")
        self.Te_Strasse.setGeometry(QRect(130, 160, 331, 41))
        self.Te_Strasse.setFont(font)
        self.Te_Strasse.setTabChangesFocus(True)
        self.label_4 = QLabel(Dlg_Kunde)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 170, 91, 21))
        self.label_4.setFont(font)
        self.Te_PLZ = QPlainTextEdit(Dlg_Kunde)
        self.Te_PLZ.setObjectName(u"Te_PLZ")
        self.Te_PLZ.setGeometry(QRect(540, 160, 131, 41))
        self.Te_PLZ.setFont(font)
        self.Te_PLZ.setTabChangesFocus(True)
        self.label_5 = QLabel(Dlg_Kunde)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(490, 170, 51, 21))
        self.label_5.setFont(font)
        self.Te_Ort = QPlainTextEdit(Dlg_Kunde)
        self.Te_Ort.setObjectName(u"Te_Ort")
        self.Te_Ort.setGeometry(QRect(730, 160, 461, 41))
        self.Te_Ort.setFont(font)
        self.Te_Ort.setTabChangesFocus(True)
        self.label_6 = QLabel(Dlg_Kunde)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(690, 170, 91, 21))
        self.label_6.setFont(font)
        self.Te_EMail = QPlainTextEdit(Dlg_Kunde)
        self.Te_EMail.setObjectName(u"Te_EMail")
        self.Te_EMail.setGeometry(QRect(540, 220, 651, 41))
        self.Te_EMail.setFont(font)
        self.Te_EMail.setTabChangesFocus(True)
        self.label_7 = QLabel(Dlg_Kunde)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(480, 230, 91, 21))
        self.label_7.setFont(font)
        self.label_8 = QLabel(Dlg_Kunde)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 290, 91, 21))
        self.label_8.setFont(font)
        self.Te_Mobile = QPlainTextEdit(Dlg_Kunde)
        self.Te_Mobile.setObjectName(u"Te_Mobile")
        self.Te_Mobile.setGeometry(QRect(130, 280, 331, 41))
        self.Te_Mobile.setFont(font)
        self.Te_Mobile.setTabChangesFocus(True)
        self.label_9 = QLabel(Dlg_Kunde)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(500, 290, 41, 21))
        self.label_9.setFont(font)
        self.Te_Tel = QPlainTextEdit(Dlg_Kunde)
        self.Te_Tel.setObjectName(u"Te_Tel")
        self.Te_Tel.setGeometry(QRect(540, 280, 651, 41))
        self.Te_Tel.setFont(font)
        self.Te_Tel.setTabChangesFocus(True)
        self.label_10 = QLabel(Dlg_Kunde)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 341, 91, 21))
        self.label_10.setFont(font)
        self.Te_Hinweis = QPlainTextEdit(Dlg_Kunde)
        self.Te_Hinweis.setObjectName(u"Te_Hinweis")
        self.Te_Hinweis.setGeometry(QRect(130, 340, 1061, 71))
        self.Te_Hinweis.setFont(font)
        self.Te_Hinweis.setTabChangesFocus(True)
        self.Te_Titel = QPlainTextEdit(Dlg_Kunde)
        self.Te_Titel.setObjectName(u"Te_Titel")
        self.Te_Titel.setGeometry(QRect(240, 100, 71, 41))
        self.Te_Titel.setFont(font)
        self.Te_Titel.setTabChangesFocus(True)
        self.label_12 = QLabel(Dlg_Kunde)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(180, 110, 51, 21))
        self.label_12.setFont(font)
        self.label_11 = QLabel(Dlg_Kunde)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 230, 91, 21))
        self.label_11.setFont(font)
        self.Te_Land = QPlainTextEdit(Dlg_Kunde)
        self.Te_Land.setObjectName(u"Te_Land")
        self.Te_Land.setGeometry(QRect(130, 220, 331, 41))
        self.Te_Land.setFont(font)
        self.Te_Land.setTabChangesFocus(True)
        self.le_Umsatz = QLineEdit(Dlg_Kunde)
        self.le_Umsatz.setObjectName(u"le_Umsatz")
        self.le_Umsatz.setEnabled(False)
        self.le_Umsatz.setGeometry(QRect(480, 20, 241, 41))
        font1 = QFont()
        font1.setPointSize(24)
        font1.setBold(True)
        self.le_Umsatz.setFont(font1)
        self.le_Umsatz.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_13 = QLabel(Dlg_Kunde)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(320, 20, 151, 31))
        self.label_13.setFont(font)
        QWidget.setTabOrder(self.Te_Anrede, self.Te_Titel)
        QWidget.setTabOrder(self.Te_Titel, self.Te_Vorname)
        QWidget.setTabOrder(self.Te_Vorname, self.Te_Nachname)
        QWidget.setTabOrder(self.Te_Nachname, self.Te_Strasse)
        QWidget.setTabOrder(self.Te_Strasse, self.Te_PLZ)
        QWidget.setTabOrder(self.Te_PLZ, self.Te_Ort)
        QWidget.setTabOrder(self.Te_Ort, self.Te_Land)
        QWidget.setTabOrder(self.Te_Land, self.Te_EMail)
        QWidget.setTabOrder(self.Te_EMail, self.Te_Mobile)
        QWidget.setTabOrder(self.Te_Mobile, self.Te_Tel)
        QWidget.setTabOrder(self.Te_Tel, self.Te_Hinweis)

        self.retranslateUi(Dlg_Kunde)
        self.buttonBox.accepted.connect(Dlg_Kunde.accept)
        self.buttonBox.rejected.connect(Dlg_Kunde.reject)

        QMetaObject.connectSlotsByName(Dlg_Kunde)
    # setupUi

    def retranslateUi(self, Dlg_Kunde):
        Dlg_Kunde.setWindowTitle(QCoreApplication.translate("Dlg_Kunde", u"Neuanlage Kunden", None))
        self.label.setText(QCoreApplication.translate("Dlg_Kunde", u"Anrede:", None))
        self.Te_Vorname.setPlainText("")
        self.label_3.setText(QCoreApplication.translate("Dlg_Kunde", u"Nachname:", None))
        self.label_2.setText(QCoreApplication.translate("Dlg_Kunde", u"Vorname:", None))
        self.Te_Strasse.setPlainText("")
        self.label_4.setText(QCoreApplication.translate("Dlg_Kunde", u"Stra\u00dfe:", None))
        self.Te_PLZ.setPlainText("")
        self.label_5.setText(QCoreApplication.translate("Dlg_Kunde", u"PLZ:", None))
        self.label_6.setText(QCoreApplication.translate("Dlg_Kunde", u"Ort:", None))
        self.Te_EMail.setPlainText("")
        self.label_7.setText(QCoreApplication.translate("Dlg_Kunde", u"EMail:", None))
        self.label_8.setText(QCoreApplication.translate("Dlg_Kunde", u"Mobile:", None))
        self.label_9.setText(QCoreApplication.translate("Dlg_Kunde", u"Tel.:", None))
        self.label_10.setText(QCoreApplication.translate("Dlg_Kunde", u"Hinweis:", None))
        self.label_12.setText(QCoreApplication.translate("Dlg_Kunde", u"Titel:", None))
        self.label_11.setText(QCoreApplication.translate("Dlg_Kunde", u"Land:", None))
        self.le_Umsatz.setText(QCoreApplication.translate("Dlg_Kunde", u"0", None))
        self.label_13.setText(QCoreApplication.translate("Dlg_Kunde", u"Gesamtumsatz:", None))
    # retranslateUi

