# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dlg_buchung.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QDateEdit,
    QDialog, QDialogButtonBox, QGroupBox, QLabel,
    QLineEdit, QSizePolicy, QWidget)

class Ui_Dlg_Buchung(object):
    def setupUi(self, Dlg_Buchung):
        if not Dlg_Buchung.objectName():
            Dlg_Buchung.setObjectName(u"Dlg_Buchung")
        Dlg_Buchung.resize(1012, 790)
        Dlg_Buchung.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.buttonBox = QDialogButtonBox(Dlg_Buchung)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(10, 740, 1051, 32))
        font = QFont()
        font.setPointSize(16)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.label = QLabel(Dlg_Buchung)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(22, 36, 101, 41))
        self.label.setFont(font)
        self.label_2 = QLabel(Dlg_Buchung)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(22, 96, 101, 41))
        self.label_2.setFont(font)
        self.label_3 = QLabel(Dlg_Buchung)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(402, 96, 101, 41))
        self.label_3.setFont(font)
        self.label_4 = QLabel(Dlg_Buchung)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QRect(792, 96, 101, 41))
        self.label_4.setFont(font)
        self.gb_Preise = QGroupBox(Dlg_Buchung)
        self.gb_Preise.setObjectName(u"gb_Preise")
        self.gb_Preise.setGeometry(QRect(30, 310, 891, 201))
        self.label_5 = QLabel(self.gb_Preise)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 30, 101, 41))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.gb_Preise)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(310, 30, 101, 41))
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.gb_Preise)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(610, 30, 101, 41))
        self.label_7.setFont(font)
        self.label_8 = QLabel(self.gb_Preise)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QRect(20, 110, 101, 41))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.gb_Preise)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(300, 110, 111, 41))
        self.label_9.setFont(font)
        self.label_10 = QLabel(self.gb_Preise)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QRect(590, 110, 101, 41))
        self.label_10.setFont(font)
        self.te_preis_uebern = QLineEdit(self.gb_Preise)
        self.te_preis_uebern.setObjectName(u"te_preis_uebern")
        self.te_preis_uebern.setGeometry(QRect(120, 30, 111, 41))
        self.te_preis_uebern.setFont(font)
        self.te_preis_reinigung = QLineEdit(self.gb_Preise)
        self.te_preis_reinigung.setObjectName(u"te_preis_reinigung")
        self.te_preis_reinigung.setGeometry(QRect(420, 30, 111, 41))
        self.te_preis_reinigung.setFont(font)
        self.te_preis_wp = QLineEdit(self.gb_Preise)
        self.te_preis_wp.setObjectName(u"te_preis_wp")
        self.te_preis_wp.setGeometry(QRect(690, 30, 111, 41))
        self.te_preis_wp.setFont(font)
        self.te_anzahlung = QLineEdit(self.gb_Preise)
        self.te_anzahlung.setObjectName(u"te_anzahlung")
        self.te_anzahlung.setGeometry(QRect(420, 110, 111, 41))
        self.te_anzahlung.setFont(font)
        self.te_preis_gesamt = QLineEdit(self.gb_Preise)
        self.te_preis_gesamt.setObjectName(u"te_preis_gesamt")
        self.te_preis_gesamt.setEnabled(False)
        self.te_preis_gesamt.setGeometry(QRect(120, 110, 111, 41))
        self.te_preis_gesamt.setFont(font)
        self.te_rest = QLineEdit(self.gb_Preise)
        self.te_rest.setObjectName(u"te_rest")
        self.te_rest.setEnabled(False)
        self.te_rest.setGeometry(QRect(690, 110, 111, 41))
        self.te_rest.setFont(font)
        self.gb_Reinigung = QGroupBox(Dlg_Buchung)
        self.gb_Reinigung.setObjectName(u"gb_Reinigung")
        self.gb_Reinigung.setGeometry(QRect(30, 530, 891, 131))
        self.label_12 = QLabel(self.gb_Reinigung)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(450, 40, 161, 31))
        self.label_12.setFont(font)
        self.cb_betten_beziehen = QCheckBox(self.gb_Reinigung)
        self.cb_betten_beziehen.setObjectName(u"cb_betten_beziehen")
        self.cb_betten_beziehen.setGeometry(QRect(230, 40, 201, 31))
        self.cb_betten_beziehen.setFont(font)
        self.cb_betten_beziehen.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.cb_betten_beziehen.setChecked(True)
        self.cb_Babyset = QCheckBox(self.gb_Reinigung)
        self.cb_Babyset.setObjectName(u"cb_Babyset")
        self.cb_Babyset.setGeometry(QRect(50, 80, 201, 31))
        self.cb_Babyset.setFont(font)
        self.cb_Babyset.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.label_14 = QLabel(self.gb_Reinigung)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(690, 40, 111, 31))
        self.label_14.setFont(font)
        self.te_anz_wp_e = QLineEdit(self.gb_Reinigung)
        self.te_anz_wp_e.setObjectName(u"te_anz_wp_e")
        self.te_anz_wp_e.setGeometry(QRect(620, 40, 31, 31))
        self.te_anz_wp_e.setFont(font)
        self.te_anz_wp_k = QLineEdit(self.gb_Reinigung)
        self.te_anz_wp_k.setObjectName(u"te_anz_wp_k")
        self.te_anz_wp_k.setGeometry(QRect(810, 40, 31, 31))
        self.te_anz_wp_k.setFont(font)
        self.cb_reinigung = QCheckBox(self.gb_Reinigung)
        self.cb_reinigung.setObjectName(u"cb_reinigung")
        self.cb_reinigung.setGeometry(QRect(50, 40, 201, 31))
        self.cb_reinigung.setFont(font)
        self.cb_reinigung.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.cb_reinigung.setChecked(True)
        self.gb_Gste = QGroupBox(Dlg_Buchung)
        self.gb_Gste.setObjectName(u"gb_Gste")
        self.gb_Gste.setGeometry(QRect(30, 170, 891, 131))
        self.label_15 = QLabel(self.gb_Gste)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 30, 121, 41))
        self.label_15.setFont(font)
        self.label_16 = QLabel(self.gb_Gste)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(340, 30, 71, 41))
        self.label_16.setFont(font)
        self.label_17 = QLabel(self.gb_Gste)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(610, 30, 71, 41))
        self.label_17.setFont(font)
        self.te_anz_erwachsene = QLineEdit(self.gb_Gste)
        self.te_anz_erwachsene.setObjectName(u"te_anz_erwachsene")
        self.te_anz_erwachsene.setGeometry(QRect(150, 30, 31, 41))
        self.te_anz_erwachsene.setFont(font)
        self.te_anz_kinder = QLineEdit(self.gb_Gste)
        self.te_anz_kinder.setObjectName(u"te_anz_kinder")
        self.te_anz_kinder.setGeometry(QRect(420, 30, 31, 41))
        self.te_anz_kinder.setFont(font)
        self.te_anz_hunde = QLineEdit(self.gb_Gste)
        self.te_anz_hunde.setObjectName(u"te_anz_hunde")
        self.te_anz_hunde.setGeometry(QRect(690, 30, 31, 41))
        self.te_anz_hunde.setFont(font)
        self.cb_Steuer = QCheckBox(Dlg_Buchung)
        self.cb_Steuer.setObjectName(u"cb_Steuer")
        self.cb_Steuer.setGeometry(QRect(50, 670, 251, 31))
        self.cb_Steuer.setFont(font)
        self.cb_Steuer.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.cb_Steuer.setChecked(True)
        self.cb_Storno = QCheckBox(Dlg_Buchung)
        self.cb_Storno.setObjectName(u"cb_Storno")
        self.cb_Storno.setGeometry(QRect(820, 670, 101, 31))
        self.cb_Storno.setFont(font)
        self.cb_Storno.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.lb_name = QLabel(Dlg_Buchung)
        self.lb_name.setObjectName(u"lb_name")
        self.lb_name.setGeometry(QRect(410, 40, 511, 41))
        font1 = QFont()
        font1.setPointSize(24)
        self.lb_name.setFont(font1)
        self.te_wohnung = QLineEdit(Dlg_Buchung)
        self.te_wohnung.setObjectName(u"te_wohnung")
        self.te_wohnung.setGeometry(QRect(130, 40, 31, 41))
        self.te_wohnung.setFont(font)
        self.dt_vom = QDateEdit(Dlg_Buchung)
        self.dt_vom.setObjectName(u"dt_vom")
        self.dt_vom.setGeometry(QRect(130, 100, 121, 41))
        self.dt_vom.setFont(font)
        self.dt_bis = QDateEdit(Dlg_Buchung)
        self.dt_bis.setObjectName(u"dt_bis")
        self.dt_bis.setGeometry(QRect(460, 100, 121, 41))
        self.dt_bis.setFont(font)
        self.te_tage = QLineEdit(Dlg_Buchung)
        self.te_tage.setObjectName(u"te_tage")
        self.te_tage.setEnabled(False)
        self.te_tage.setGeometry(QRect(860, 100, 61, 41))
        self.te_tage.setFont(font)
        QWidget.setTabOrder(self.te_wohnung, self.dt_vom)
        QWidget.setTabOrder(self.dt_vom, self.dt_bis)
        QWidget.setTabOrder(self.dt_bis, self.te_anz_erwachsene)
        QWidget.setTabOrder(self.te_anz_erwachsene, self.te_anz_kinder)
        QWidget.setTabOrder(self.te_anz_kinder, self.te_anz_hunde)
        QWidget.setTabOrder(self.te_anz_hunde, self.te_preis_uebern)
        QWidget.setTabOrder(self.te_preis_uebern, self.te_preis_reinigung)
        QWidget.setTabOrder(self.te_preis_reinigung, self.te_preis_wp)
        QWidget.setTabOrder(self.te_preis_wp, self.te_anzahlung)
        QWidget.setTabOrder(self.te_anzahlung, self.cb_reinigung)
        QWidget.setTabOrder(self.cb_reinigung, self.cb_betten_beziehen)
        QWidget.setTabOrder(self.cb_betten_beziehen, self.te_anz_wp_e)
        QWidget.setTabOrder(self.te_anz_wp_e, self.te_anz_wp_k)
        QWidget.setTabOrder(self.te_anz_wp_k, self.cb_Babyset)
        QWidget.setTabOrder(self.cb_Babyset, self.cb_Steuer)
        QWidget.setTabOrder(self.cb_Steuer, self.cb_Storno)
        QWidget.setTabOrder(self.cb_Storno, self.te_rest)
        QWidget.setTabOrder(self.te_rest, self.te_preis_gesamt)

        self.retranslateUi(Dlg_Buchung)
        self.buttonBox.accepted.connect(Dlg_Buchung.accept)
        self.buttonBox.rejected.connect(Dlg_Buchung.reject)

        QMetaObject.connectSlotsByName(Dlg_Buchung)
    # setupUi

    def retranslateUi(self, Dlg_Buchung):
        Dlg_Buchung.setWindowTitle(QCoreApplication.translate("Dlg_Buchung", u"Neuanlage Buchung", None))
        self.label.setText(QCoreApplication.translate("Dlg_Buchung", u"Wohnung:", None))
        self.label_2.setText(QCoreApplication.translate("Dlg_Buchung", u"Vom:", None))
        self.label_3.setText(QCoreApplication.translate("Dlg_Buchung", u"Bis", None))
        self.label_4.setText(QCoreApplication.translate("Dlg_Buchung", u"Tage:", None))
        self.gb_Preise.setTitle(QCoreApplication.translate("Dlg_Buchung", u"Preise", None))
        self.label_5.setText(QCoreApplication.translate("Dlg_Buchung", u"\u00dcbern.:", None))
        self.label_6.setText(QCoreApplication.translate("Dlg_Buchung", u"Reinigung:", None))
        self.label_7.setText(QCoreApplication.translate("Dlg_Buchung", u"W\u00e4sche:", None))
        self.label_8.setText(QCoreApplication.translate("Dlg_Buchung", u"Gesamt:", None))
        self.label_9.setText(QCoreApplication.translate("Dlg_Buchung", u"Anzahlung:", None))
        self.label_10.setText(QCoreApplication.translate("Dlg_Buchung", u"Rest:", None))
        self.te_preis_uebern.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_preis_reinigung.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_preis_wp.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_anzahlung.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_preis_gesamt.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_rest.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.gb_Reinigung.setTitle(QCoreApplication.translate("Dlg_Buchung", u"Reinigung/W\u00e4sche", None))
        self.label_12.setText(QCoreApplication.translate("Dlg_Buchung", u"WP_Erwachsene:", None))
        self.cb_betten_beziehen.setText(QCoreApplication.translate("Dlg_Buchung", u"Betten beziehen?", None))
        self.cb_Babyset.setText(QCoreApplication.translate("Dlg_Buchung", u"Babyset?", None))
        self.label_14.setText(QCoreApplication.translate("Dlg_Buchung", u"WP_Kinder:", None))
        self.te_anz_wp_e.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_anz_wp_k.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.cb_reinigung.setText(QCoreApplication.translate("Dlg_Buchung", u"Reinigung?", None))
        self.gb_Gste.setTitle(QCoreApplication.translate("Dlg_Buchung", u"Anzahl G\u00e4ste", None))
        self.label_15.setText(QCoreApplication.translate("Dlg_Buchung", u"Erwachsene:", None))
        self.label_16.setText(QCoreApplication.translate("Dlg_Buchung", u"Kinder:", None))
        self.label_17.setText(QCoreApplication.translate("Dlg_Buchung", u"Hunde:", None))
        self.te_anz_erwachsene.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_anz_kinder.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_anz_hunde.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.cb_Steuer.setText(QCoreApplication.translate("Dlg_Buchung", u"Zweitwohnungssteuer?", None))
        self.cb_Storno.setText(QCoreApplication.translate("Dlg_Buchung", u"Storno", None))
        self.lb_name.setText("")
        self.te_wohnung.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
        self.te_tage.setText(QCoreApplication.translate("Dlg_Buchung", u"0", None))
    # retranslateUi

